"""adauga impedanta retea amonte pe proiect

Revision ID: 74bb44efc4c5
Revises: 98bd9108b99c
Create Date: 2026-07-15 00:40:34.214306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74bb44efc4c5'
down_revision = '98bd9108b99c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proiecte', sa.Column('impedanta_retea_amonte_ohm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proiecte', 'impedanta_retea_amonte_ohm')
    # ### end Alembic commands ###
