"""catalog componente si legaturi circuit receptor

Revision ID: 98bd9108b99c
Revises: b13c3d63463f
Create Date: 2026-07-15 00:36:44.802026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bd9108b99c'
down_revision = 'b13c3d63463f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('componente_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.Enum('protectie', 'cablu', 'corp_iluminat', 'priza', 'intrerupator', 'tablou', 'doza', 'altele', name='categorie_componenta'), nullable=False),
    sa.Column('nume', sa.String(length=255), nullable=False),
    sa.Column('producator', sa.String(length=255), nullable=True),
    sa.Column('cod_produs', sa.String(length=255), nullable=True),
    sa.Column('specificatii', sa.JSON(), nullable=False),
    sa.Column('pret_estimativ', sa.Float(), nullable=True),
    sa.Column('unitate_masura', sa.String(length=50), nullable=False),
    sa.Column('simbol_ref', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('circuite', sa.Column('protectie_selectata_id', sa.Integer(), nullable=True))
    op.add_column('circuite', sa.Column('protectie_auto', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('circuite', sa.Column('cablu_selectat_id', sa.Integer(), nullable=True))
    op.add_column('circuite', sa.Column('cablu_auto', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_foreign_key(None, 'circuite', 'componente_catalog', ['cablu_selectat_id'], ['id'])
    op.create_foreign_key(None, 'circuite', 'componente_catalog', ['protectie_selectata_id'], ['id'])
    op.add_column('receptori', sa.Column('componenta_id', sa.Integer(), nullable=True))
    op.add_column('receptori', sa.Column('cantitate', sa.Float(), nullable=False, server_default='1.0'))
    op.create_foreign_key(None, 'receptori', 'componente_catalog', ['componenta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receptori', type_='foreignkey')
    op.drop_column('receptori', 'cantitate')
    op.drop_column('receptori', 'componenta_id')
    op.drop_constraint(None, 'circuite', type_='foreignkey')
    op.drop_constraint(None, 'circuite', type_='foreignkey')
    op.drop_column('circuite', 'cablu_auto')
    op.drop_column('circuite', 'cablu_selectat_id')
    op.drop_column('circuite', 'protectie_auto')
    op.drop_column('circuite', 'protectie_selectata_id')
    op.drop_table('componente_catalog')
    # ### end Alembic commands ###
