"""schema initiala

Revision ID: b13c3d63463f
Revises: 
Create Date: 2026-07-14 23:50:34.555172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13c3d63463f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('proiectant', 'verificator', 'administrator', name='rol_utilizator'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('proiecte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=255), nullable=False),
    sa.Column('beneficiar', sa.String(length=255), nullable=False),
    sa.Column('tip_cladire', sa.Enum('rezidential', 'industrial', name='tip_cladire'), nullable=False),
    sa.Column('adresa', sa.String(length=500), nullable=True),
    sa.Column('tensiune_alimentare', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tablouri_electrice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proiect_id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=255), nullable=False),
    sa.Column('putere_instalata', sa.Float(), nullable=True),
    sa.Column('putere_calcul', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['proiect_id'], ['proiecte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circuite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tablou_id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=255), nullable=False),
    sa.Column('tip', sa.Enum('monofazat', 'trifazat', name='tip_circuit'), nullable=False),
    sa.Column('mod_pozare', sa.String(length=100), nullable=False),
    sa.Column('lungime_cablu_m', sa.Float(), nullable=False),
    sa.Column('sectiune_mm2', sa.Float(), nullable=True),
    sa.Column('curent_nominal_a', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tablou_id'], ['tablouri_electrice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calcul_rezultate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('tip_calcul', sa.String(length=100), nullable=False),
    sa.Column('valoare', sa.Float(), nullable=False),
    sa.Column('unitate', sa.String(length=50), nullable=False),
    sa.Column('standard_referinta', sa.String(length=255), nullable=False),
    sa.Column('status_conformitate', sa.Enum('conform', 'neconform', name='status_conformitate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receptori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=255), nullable=False),
    sa.Column('tip', sa.Enum('iluminat', 'priza', 'motor', 'forta', name='tip_receptor'), nullable=False),
    sa.Column('putere_nominala_w', sa.Float(), nullable=False),
    sa.Column('cos_phi', sa.Float(), nullable=False),
    sa.Column('ku', sa.Float(), nullable=False),
    sa.Column('ks', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receptori')
    op.drop_table('calcul_rezultate')
    op.drop_table('circuite')
    op.drop_table('tablouri_electrice')
    op.drop_table('proiecte')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
